preprocess_device: gpu # Set to cpu if your GPU memory is below 32GB
dataset: Debug

train_datasets: ${oc.select:_dataset_lookup.${dataset}.train,${dataset}}
eval_datasets: ${oc.select:_dataset_lookup.${dataset}.eval,${dataset}}
task_names: ['cora_link','cora_node','pubmed_link','pubmed_node','arxiv','wn18rr','fb15k237','wikics','chemblpre','chempcba','chemhiv']
# task_names: ['cora_link','cora_node','pubmed_link','pubmed_node','arxiv','wikics']


llm_name: ST   # choice: [ST, llama2_7b, llama2_13b, e5, roberta]
llm_b_size: 1
batch_size: 512
train_sample_size: -1

_all_datasets: [
  cora,
  pubmed,
  arxiv,
  wikics,
  amazon-ratings,
  wn18rr,
  fb15k237,
  # chemhiv,
  # chemblpre,
  # chempcba
]

_dataset_lookup:
  Xcora:
    eval: [cora]
    train: ${_all_datasets}

  Xpubmed:
    eval: [pubmed]
    train: ${_all_datasets}
  
  Xarxiv: 
    eval: [arxiv]
    train: ${_all_datasets}

  Xwikics:  
    eval: [wikics]
    train: ${_all_datasets}

  Xwn18rr:
    eval: [wn18rr]
    train: ${_all_datasets}

  Xfb15k237:
    eval: [fb15k237]
    train: ${_all_datasets}
  
  Xchemhiv:
    eval: [chemhiv]
    train: ${_all_datasets}
  
  Xchemblpre:
    eval: [chemblpre]
    train: ${_all_datasets}

  Xchempcba:
    eval: [chempcba]
    train: ${_all_datasets}



data_config:
  E2E-node: &E2E-node
    task_level: e2e_node
    preprocess: null
    construct: ConstructNodeCls
    args:
      walk_length: null
      single_prompt_edge: True
    eval_metric: acc
    eval_func: classification_func
    eval_mode: max

  arxiv: &arxiv
    <<: *E2E-node
    dataset_name: arxiv
    dataset_splitter: ArxivSplitter
    process_label_func: process_pth_label
    num_classes: 40

  logic_arxiv: &logic_arxiv
    <<: *arxiv
    task_level: logic_e2e
    process_label_func: process_logic_label
    eval_metric: auc
    eval_func: flat_auc

  cora: &cora
    <<: *E2E-node   # 包含了E2E-node的所有配置
    dataset_name: Cora
    dataset_splitter: CiteSplitter
    process_label_func: process_int_label
    num_classes: 7

  logic_cora: &logic_cora
    <<: *cora  
    task_level: logic_e2e
    process_label_func: process_logic_label
    eval_metric: auc
    eval_func: flat_auc

  pubmed: &pubmed
    <<: *E2E-node
    dataset_name: pubmed
    dataset_splitter: CiteSplitter
    process_label_func: process_int_label
    num_classes: 3

  wikics: &wikics
    <<: *E2E-node
    dataset_name: wikics
    dataset_splitter: WikiSplitter
    process_label_func: process_pth_label
    num_classes: 10

  amazon-ratings: &amazon-ratings
    <<: *E2E-node
    dataset_name: amazon-ratings
    dataset_splitter: AmazonRatingsSplitter
    process_label_func: process_int_label
    num_classes: 5

  computers: &computers
    <<: *E2E-node
    dataset_name: computers
    num_classes: 10


  link-eval-args: &link-eval-args
    remove_edge: False
    walk_length: null

  E2E-link: &E2E-link
    task_level: e2e_link
    args:
      remove_edge: True
      walk_length: null

  E2E-link-cite: &E2E-link-cite
    <<: *E2E-link
    preprocess: LinkConstructGraph
    construct: ConstructLinkCls
    dataset_splitter: CiteLinkSplitter
    process_label_func: process_int_label
    eval_metric: auc
    eval_func: binary_auc_func
    num_classes: 2
    eval_mode: max

  cora_link: &cora_link
    <<: *E2E-link-cite
    dataset_name: Cora

  cora_link_eval:
    <<: *cora_link
    args:
      <<: *link-eval-args

  pubmed_link: &pubmed_link
    <<: *E2E-link-cite
    dataset_name: pubmed

  pubmed_link_eval:
    <<: *pubmed_link
    args:
      <<: *link-eval-args

  E2E-link-KG: &E2E-link-KG
    <<: *E2E-link
    dataset_splitter: KGSplitter
    preprocess: KGConstructEdgeList
    construct: ConstructKG
    process_label_func: process_int_label
    eval_metric: acc
    eval_func: classification_func
    eval_mode: max

  wn18rr: &wn18rr
    <<: *E2E-link-KG
    dataset_name: wn18rr
    num_classes: 11

  wn18rr_eval: &wn18rr_eval
    <<: *wn18rr
    args:
      <<: *link-eval-args

  fb15k237: &fb15k237
    <<: *E2E-link-KG
    dataset_name: fb15k237
    num_classes: 237

  fb15k237_eval: &fb15k237_eval
    <<: *fb15k237
    args:
      <<: *link-eval-args

  E2E-graph: &E2E-graph
    task_level: e2e_graph
    dataset_splitter: MolSplitter
    preprocess: null
    construct: ConstructMolCls
    args:
      walk_length: null
    eval_mode: max

  chemblpre: &chemblpre
    <<: *E2E-graph
    dataset_name: chemblpre
    process_label_func: process_positive_negative_multi_label
    eval_metric: apr
    eval_func: binary_apr_func
    num_classes: 1295

  chempcba: &chempcba
    <<: *E2E-graph
    dataset_name: chempcba
    process_label_func: process_positive_negative_multi_label
    eval_metric: apr
    eval_func: binary_apr_func
    num_classes: 128

  chempcba_eval: &chempcba_eval
    <<: *chempcba
    process_label_func: process_label_positive_only

  chemhiv: &chemhiv
    <<: *E2E-graph
    dataset_name: chemhiv
    process_label_func: process_reverse_binary_label
    eval_metric: auc
    eval_func: binary_auc_func
    num_classes: 2

  LR-node: &LR-node
    task_level: lr_node
    construct: ConstructFSTask
    args:
      walk_length: null
      single_prompt_edge: True
    eval_metric: acc
    eval_func: classification_func
    eval_mode: max

  arxiv_fs: &arxiv_fs
    <<: *LR-node
    dataset_name: arxiv
    dataset_splitter: ArxivFSSplitter
    process_label_func: process_pth_label
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 5
      k_shot: 5
      min_k_shot: 0
      base_construct: ConstructNodeCls
      no_class_node: True
    num_classes: 5

  arxiv_fs_51:
    <<: *arxiv_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 5
      k_shot: 1
      base_construct: ConstructNodeCls
      no_class_node: True


  arxiv_fs_53:
    <<: *arxiv_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 5
      k_shot: 3
      base_construct: ConstructNodeCls
      no_class_node: True

  arxiv_fs_55:
    <<: *arxiv_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 5
      k_shot: 5
      base_construct: ConstructNodeCls
      no_class_node: True

  cora_fs: &cora_fs
    <<: *LR-node
    dataset_name: cora
    dataset_splitter: CiteFSSplitter
    process_label_func: process_int_label
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 2
      k_shot: 1
      base_construct: ConstructNodeCls
      no_class_node: True
    num_classes: 2

  cora_fs_21:
    <<: *cora_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 2
      k_shot: 1
      base_construct: ConstructNodeCls
      no_class_node: True
    num_classes: 2


  cora_fs_23:
    <<: *cora_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 2
      k_shot: 3
      base_construct: ConstructNodeCls
      no_class_node: True
    num_classes: 2


  cora_fs_25:
    <<: *cora_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 2
      k_shot: 5
      base_construct: ConstructNodeCls
      no_class_node: True
    num_classes: 2


  cora_fs_71:
    <<: *cora_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 7
      k_shot: 1
      base_construct: ConstructNodeCls
      no_class_node: True
    num_classes: 7


  cora_fs_73:
    <<: *cora_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 7
      k_shot: 3
      base_construct: ConstructNodeCls
      no_class_node: True
    num_classes: 7


  cora_fs_75:
    <<: *cora_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 7
      k_shot: 5
      base_construct: ConstructNodeCls
      no_class_node: True
    num_classes: 7


  LR-link: &LR-link
    task_level: lr_link
    construct: ConstructFSTask
    preprocess: KGConstructEdgeList
    args:
      walk_length: null
      single_prompt_edge: True
    eval_metric: acc
    eval_func: classification_func
    eval_mode: max

  fb15k237_fs: &fb15k237_fs
    <<: *LR-link
    dataset_name: fb15k237
    dataset_splitter: KGFSTrainSplitter
    process_label_func: process_int_label
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 20
      k_shot: 5
      min_k_shot: 1
      min_n_way: 10
      base_construct: ConstructKG
      no_class_node: True
      remove_edge: True
    num_classes: 20

  fb15k237_fs_101:
    <<: *fb15k237_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 10
      k_shot: 1
      base_construct: ConstructKG
      no_class_node: True
      remove_edge: True
    num_classes: 10


  fb15k237_fs_103:
    <<: *fb15k237_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 10
      k_shot: 3
      base_construct: ConstructKG
      no_class_node: True
      remove_edge: True
    num_classes: 10

  fb15k237_fs_105:
    <<: *fb15k237_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 10
      k_shot: 5
      base_construct: ConstructKG
      no_class_node: True
      remove_edge: True
    num_classes: 10


  fb15k237_fs_201:
    <<: *fb15k237_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 20
      k_shot: 1
      base_construct: ConstructKG
      no_class_node: True
      remove_edge: True
    num_classes: 20


  fb15k237_fs_203:
    <<: *fb15k237_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 20
      k_shot: 3
      base_construct: ConstructKG
      no_class_node: True
      remove_edge: True
    num_classes: 20

  fb15k237_fs_205:
    <<: *fb15k237_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 20
      k_shot: 5
      base_construct: ConstructKG
      no_class_node: True
      remove_edge: True
    num_classes: 20


  wn18rr_fs: &wn18rr_fs
    <<: *LR-link
    dataset_name: wn18rr
    dataset_splitter: KGFSSplitter
    process_label_func: process_int_label
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 5
      k_shot: 1
      base_construct: ConstructKG
      no_class_node: True
      remove_edge: False
    num_classes: 5


  wn18rr_fs_51:
    <<: *wn18rr_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 5
      k_shot: 1
      base_construct: ConstructKG
      no_class_node: True
      remove_edge: False
    num_classes: 5

  wn18rr_fs_53:
    <<: *wn18rr_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 5
      k_shot: 3
      base_construct: ConstructKG
      no_class_node: True
      remove_edge: False
    num_classes: 5


  wn18rr_fs_55:
    <<: *wn18rr_fs
    args:
      walk_length: null
      single_prompt_edge: True
      n_way: 5
      k_shot: 5
      base_construct: ConstructKG
      no_class_node: True
      remove_edge: False
    num_classes: 5


# ! Dataset Meta Data
_ds_meta_data:
  cora: pyg, Planetoid.Cora
  pubmed: pyg, Planetoid.PubMed
  arxiv: ofa, SingleTextGraph.arxiv
  wikics: ofa, SingleTextGraph.WikiCS
  amazon-ratings: pyg, HeterophilousGraphDataset.Amazon-ratings
  computers: pyg, Amazon.Computers
  # link prediction on Knowledge graphs
  fb15k237: ofa, KnowledgeGraph.FB15K237
  wn18rr: ofa, KnowledgeGraph.WN18RR
  